nithin999989/LeetCodeSolutions

- Swap Nodes In Pairs
Solution to leetcode question Swap Nodes in Pairs.
> Create Swap Nodes In Pairs

- 973. K Closest Points to Origin/K Closest Points to Origin.cpp
- 973. K Closest Points to Origin/README.md
I've added my solution to the problem 973. K Closest Points to Origin on Leetcode as part of Hacktoberfest 2022. Please review my PR and the 'hacktoberfest' and 'hacktoberfest-accepted' tags to it. @Nithin108
> Added solution to Problem 973 on Leetcode as part of Hacktoberfest 2022

- leetcode 451. sort characters by frequency
Hey @Nithin108 can you please add this solution to your repository and label it hactoberfest and hactoberaccepted
> Leetcode 451 Sort characters by frequency

- 205. Isomorphic Strings
Hey @Nithin108 This is the solution for Leetcode 205,can you add it to your repository and label it as hactober
> 205. Isomorphic Strings

- 1903. Largest Odd Number in String/Java_Code
- 1903. Largest Odd Number in String/Readme.md
- 990. Satisfiability of Equality Equations/Java program
- 990. Satisfiability of Equality Equations/Readme.md
Hey @Nithin108 ,Can you add this to your repository and label it as hacktoberfest
> 1903. Largest Odd Number in String

- 17-letter-combinations-of-a-phone-number/17-letter-combinations.java
- 17-letter-combinations-of-a-phone-number/README.md
- README.md
Added Leetcode question number 17 and updated the readme file to include the name and link of the questions solved and recorded
> Added Lettecode question and updated Readme

- 53-Maximum-Subarray/MaximumSubarray.cpp
Added C++ code for Maximum Subarray Question
> add 53. Maximum Subarray

- 62. Unique Paths/Readme.md
- 62. Unique Paths/program
hey @Nithin108 can you please add this to your repository and label it as hactoberfest
> added solution to 62. Unique Paths

- 52-n-queens-II/52-n-queens-II.java
- 52-n-queens-II/README.md
- README.md
Added Leetcode N Queens Problem II
> Added N Queens II

- Happy-Number-Leetcode/README.md
- Happy-Number-Leetcode/happyNumber.cpp
Leetcode Problem Number 202 Solution .
> This is the Solution of Leetcode problem number 202.

- 2278-percent-of-letter-in-string/2278-percent-of-letter-in-string.java
- 2278-percent-of-letter-in-string/README.MD
- README.md
Added Leetcode percent of letter in a given string
> Added Percentage of letter

- 1295-find-num-with-even-digits/1295-find-num-with-even-digits.java
- 1295-find-num-with-even-digits/README.md
- 1672-richest-customer-wealth/1672-richest-customer-wealth.java
- 1672-richest-customer-wealth/README.md
- README.md
Added Leetcode questions 
1295) Find number with even number of digits
1672) Richest Customer wealth
> Added Leetcode Problem 1295 and 1672

- 41-first-missing-positive/41-first-missing-positive.java
- 41-first-missing-positive/README.md
- README.md
Added leetcode hard question find first missing positive and updated readme
> Added Leetcode question

- 97- Interleaving-String/97-Interleaving-String.cpp
- 97- Interleaving-String/README.md
Hacktoberfest submission for the Leetcode Que number 97
> Added the solution to the 97th Que of Leetcode

- 278-first-bad-version/278-first-bad-version.java
- README.md
Added leetcode question first bad version and updated the readme file
> Added First bad Version

- 58-length-of-last-word/58-length-of-last-word.java
- 58-length-of-last-word/README.md
- README.md
Added leetcode question find the length of the last word and updated readme file
> Added Length of last word

- 637-Average of Levels in Binary Tree/637-Average of Levels in Binary Tree.java
Added Solution to LeetCode problem 637 in Java Kindly Merge it.
> 637 Average of Level- Added

- 51. N-Queens/N-Queens.py
- 51. N-Queens/NOTES.md
- 51. N-Queens/README.md
> 51. N-Queens

- 5-Longest-Pallindromic-substring/LongestPallindromicSubstring.java
Hey!
I have just added 5- Longest Palindromic Substring code of leetcode .
Please checkout and provide feedback
> Added Longest Palindromic Substring

- 1155. Number of Dice Rolls With Target Sum/Number of Dice Rolls With Target Sum.java
> Create Number of Dice Rolls With Target Sum.java

- 100-same-tree/100-same-tree.java
- 100-same-tree/README.md
- README.md
Added a leetcode question same tree and updated the readme file
> Added Same Tree question

- 23-merge-k-sorted-lists/mergeKSortedLists.cpp
- 23-merge-k-sorted-lists/readme.md
- README.md
I have added a solution to merge k linked lists problem and updated readme file.
> Please approve my request

- 51. N-Queens/N-Queens.py
Hi , 
Please review my pr for hacktoberfest.
Solves Issue #46
> Added N-Queens.py

- 37. Sudoku Solver/README.md
- 37. Sudoku Solver/Sudoku Solver.py
Hi ,
Please review and merge my pr for hacktoberfest .
Solves Issue #17
> Added Readme file and Sudoku Code in python

- 143-Reorder List/ReorderList.java
Added java solution for LeetCode problem 143.
> Leetcode soln for 143. Reorder List

- Linked-List-Cycle-2/Linked-list-Cycle2.cpp
- Linked-List-Cycle-2/Readme.md
- Majority Element/Majority-Element.cpp
- Majority Element/ReadMe.md
> Majority-Element-Leetcode

- 15-3Sum/3Sum.java
- 22- Generate Paranthesis/Generate Paranthesis.java
Added soln for Leetcode 15- 3sum
> Leetcode 15- 3sum

- Add two numbers.java
Added soln for LeetCode 2- Add two numbers
> Leetcode 2- Add two numbers

- 50-powx-n/Pow(x, n) | Most Optimized Solution.java
added java solution for Pow(x, n)
> Pow(x, n) | Most Optimized Solution.java

- 976-Largest-Perimeter-Triangle/README.md
- 976-Largest-Perimeter-Triangle/Solution.cpp
- 976-Largest-Perimeter-Triangle/Solution.java
-Added solution in java
-Added solution in cpp
> Added LeetCode daily problem 12th Oct 2022

- 219.Contains Duplicate II
Hi,
Please review my solution to 219th question in leetcode for Hactoberfest.
> added solution in c++ to question 219 in leetcode.

- 237-Delete-Node-in-a-Linked-List/README.md
- 237-Delete-Node-in-a-Linked-List/Solution.cpp
- 237-Delete-Node-in-a-Linked-List/Solution.java
-Added java solution
-Added cpp solution
-Added README.md
> Added LeetCode daily problem 13th Oct 2022

- 299. Bulls and cows.cpp
You are playing the Bulls and Cows game with your friend.
You write down a secret number and ask your friend to guess what the number is. When your friend makes a guess, you provide a hint with the following info:
The number of "bulls", which are digits in the guess that are in the correct position. The number of "cows", which are digits in the guess that are in your secret number but are located in the wrong position. Specifically, the non-bull digits in the guess that could be rearranged such that they become bulls. Given the secret number secret and your friend's guess guess, return the hint for your friend's guess.
The hint should be formatted as "xAyB", where x is the number of bulls and y is the number of cows. Note that both secret and guess may contain duplicate digits.
Example 1: …
> Create 299. Bulls and cows.cpp

- README.md
This is my small contribution towards the good work you are doing! Moreover, a step for HACKTOBERFEST 2022!! Kindly add the hacktoberfest tag :)
> Added Introduction to README.md

- widhtOfbinaryTree.cpp
here we use the levelOrderTraversal of binary tree and we are going to mark of node from left two right so the width of the level would be leftnode no - right node no. and by taking all level we have calculated the max width.
> 662-MaximumWidthofBT

- 1531. String-Compression-II/README.md
- 1531. String-Compression-II/Solution.java
-Added Java Solution
-Added README.md
> Added LeetCode Daily Problem 15th Oct 2022

- 1255.Maximum Score Words Formed by Letters/c.cpp
added cpp solution for the leetcode hard problem 1255.Maximum Score Words Formed by Letters
> added cpp solution

- 1335.Minimum-Difficulty-of-a-Job-Schedule/README.md
- 1335.Minimum-Difficulty-of-a-Job-Schedule/Solution.java
-Added Java Solution
-Added README.md
> Added LeetCode Daily Problem 16th Oct 2022

- 1832.Check-if-the-Sentence-Is-Pangram/README.md
- 1832.Check-if-the-Sentence-Is-Pangram/Solution.java
-Added java solution
-Added README.md
> Added LeetCode Daily problem 17th Oct 2022

- 21-Merge-Two-Sorted-Lists/Merge _Two_Sorted_Lists.java
- README.md
Please add my file to in your repository with label hacktoberfest.
> Hacktoberfest

- 99-recover-binary-search-tree/99-recover-binary-search-tree.cpp
- 99-recover-binary-search-tree/README.md
Added leetcode problem (both question and answer) 99. Recover BST
> Problem 99 Recover Binary Search Tree

- 2618. Check if Object Instance of Class/2618. Check if Object Instance of Class.js
- 2618. Check if Object Instance of Class/README.md
- 2622. Cache With Time Limit/2622. Cache With Time Limit.js
- 2622. Cache With Time Limit/README.md
> added first javascript question and its solution

- 191. Number of 1 Bits.cpp
- Peak Index in a Mountain Array.cpp
- README.md
[Peak Index in a Mountain Array](https://leetcode.com/problems/peak-index-in-a-mountain-array/)
[191. Number of 1 Bits](https://leetcode.com/problems/number-of-1-bits/)  
solution added
> 2 problems solution added

- 2623. Memoize/2623. Memoize.js
- 2623. Memoize/README.md
> added solution for 2623.memoize

- 430-flatten-douby-link-list/readme.md
- 430-flatten-douby-link-list/solution.cpp
Added one solution for leetcode question : [430. Flatten a Multilevel Doubly Linked List](https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/)
> Leetcode-430. Flatten a Multilevel Doubly Linked List

- 10.Regular Expression Matching
Using Recursive and Backtracking
> Create 10.Regular Expression Matching

- 23.Merge K Sorted Lists
Solution 1: Using Merge with Divide And Conquer - Accepted in 6 ms
> Create 23.Merge K Sorted Lists

- 25.Reverse Nodes in K Group
> Create 25.Reverse Nodes in K Group

- Substring With Concentration of all  words
> Create Substring With Concentration of all  words

- 37.Sudoku Solver
> Create 37.Sudoku Solver

- 41.First Missing Positive
> Create 41.First Missing Positive

- 2900. Longest Unequal Adjacent Groups Subsequence I/problem.md
- 2900. Longest Unequal Adjacent Groups Subsequence I/solution.cpp
A New problem is added with its solution in well commented format.
> Longest Unequal Adjecent Groups Subsequence I

- 119 - Pascal Triangle II.txt
Solution for pascal triangle II problem
> pascal triangle II

- 44 - Wildcard Matching.cpp
Created Solution for Problem 44 Leetcode Wildcard Matching.
> Create 44 - Wildcard Matching.cpp

- 275  H-Index II .cpp
- Leetcode 274 H-Index.cpp
Created Solution for Leetcode Problem 274 H-Index
> Created Leetcode 274 H-Index.cpp

- 1512.number-0f-good-pairs.cpp
solution of 1512.number-of-good-pairs  in cpp 
Time: 0ms(100%), Space: 7.6MB(57.31%)
> 1512.number-of-good-pairs solution in cpp

- 42- Trapping Rain Water .cpp
Given N non-negative integers a1,a2,....an where each represents a point at coordinate (i, ai). N vertical lines are drawn such that the two endpoints of line i is at (i, ai) and (i,0). Find two lines, which together with x-axis forms a container, such that it contains the most water.
Note : In Case of single verticle line it will not be able to hold water.
> Create 42- Trapping Rain Water .cpp

- 448-Find All Numbers Disappeared in an Array/solution.cpp
Solution for below question :
[Leet Code Question Link](https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/description/)
> 448. Find All Numbers Disappeared in an Array

- 24-Swap-Node-In-Pair/24-swap-nodes-in-pair.cpp
- 24-Swap-Node-In-Pair/README.md
Solution added for leetcode 24. Please review and add it.
> added solution for leetcode number 24

- 1470. Shuffle the Array/code.java
- 1470. Shuffle the Array/readme.md
- 1920. Build Array from Permutation/code.java
- 1920. Build Array from Permutation/readme.md
- 1929. Concatenation of Array/code.java
- 1929. Concatenation of Array/readme.md
@nithin999989 can you please add hacktoberfest label to it and merge the pr, thank you!
> Added leetcode question/answers regarding topic-arrays
